### PR TITLE
Update sponsor profile

### PR DESCRIPTION
**Pull request by yeasy**
Update the sponsor name and email.

Signed-off-by: Baohua Yang <yangbaohua@gmail.com>

### CODE REVIEW

**Comment by yeasy** [comment]
@tkuhrt tracy, can you help check why the DCO complains with the email addr?
Thanks!

**Comment by tkuhrt** [comment]
DCO — Expected "Baohua Yang <yeasy@users.noreply.github.com>", but got "Baohua Yang <yangbaohua@gmail.com>".

Looks like you git configuration on your machine is not set to match what Github ID expects. Can you check your `user.name` and `user.email` with `git config --list` to see what it contains.

**Comment by yeasy** [comment]
Yes, i just edited and submited the file change through the website, and don't know where the "yeasy@users.noreply.github.com" comes from?

**Comment by tkuhrt** [comment]
My guess is that it wants the noreply email address because your email address is not being shared publically through your Github profile.

**Comment by yeasy** [comment]
Oh, now i make it public, do you know how to re-trigger the check?

**Comment by tkuhrt** [comment]
I believe the only way to re-trigger the check is to "update" the commit.

**Pull request closed without merging**
